"""shopify stores

Revision ID: 226f3b769f0c
Revises: 664af33cb71f
Create Date: 2026-10-09 13:04:24.501267
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "226f3b769f0c"
down_revision: str | None = "664af33cb71f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APP_ROLE = "sendox_app"
TENANT_SETTING = "app.current_tenant_id"
TENANT_PREDICATE = f"tenant_id = NULLIF(current_setting('{TENANT_SETTING}', true), '')::uuid"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shopify_stores",
        sa.Column("shop_domain", sa.String(length=255), nullable=False),
        sa.Column("access_token_encrypted", sa.String(length=1024), nullable=False),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("shop_name", sa.String(length=255), nullable=True),
        sa.Column("shop_email", sa.String(length=320), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("shop_timezone", sa.String(length=64), nullable=True),
        sa.Column("installed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uninstalled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "shop_domain", name="uq_shopify_store_tenant_domain"),
    )
    op.create_index(
        op.f("ix_shopify_stores_shop_domain"), "shopify_stores", ["shop_domain"], unique=False
    )
    op.create_index(
        op.f("ix_shopify_stores_tenant_id"), "shopify_stores", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###

    # A store connection holds an access token, so it must never be readable from
    # another workspace. Same FORCE'd policy as every other tenant-scoped table;
    # tests/test_rls.py fails if a new one is added without it.
    op.execute("ALTER TABLE shopify_stores ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE shopify_stores FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON shopify_stores "
        f"USING ({TENANT_PREDICATE}) WITH CHECK ({TENANT_PREDICATE})"
    )
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON shopify_stores TO {APP_ROLE}")


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON shopify_stores")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shopify_stores_tenant_id"), table_name="shopify_stores")
    op.drop_index(op.f("ix_shopify_stores_shop_domain"), table_name="shopify_stores")
    op.drop_table("shopify_stores")
    # ### end Alembic commands ###
