"""store last indexed at

Revision ID: 6c22d20629f9
Revises: d857d55601e1
Create Date: 2026-10-10 17:36:31.909293
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Autogenerate emits postgresql.JSONB / postgresql.ENUM without importing the
# dialect, which fails at runtime inside the container rather than at review
# time. Importing it here means every generated migration has it. Ruff's unused
# import rule is waived for this file in pyproject.toml.
from sqlalchemy.dialects import postgresql

revision: str = "6c22d20629f9"
down_revision: str | None = "d857d55601e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shopify_stores", sa.Column("last_indexed_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shopify_stores", "last_indexed_at")
    # ### end Alembic commands ###
