"""contacts, events, products

Revision ID: d857d55601e1
Revises: 226f3b769f0c
Create Date: 2026-10-09 16:44:24.591623
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Autogenerate emits postgresql.JSONB / postgresql.ENUM without importing the
# dialect, which fails at runtime inside the container rather than at review
# time. Importing it here means every generated migration has it. Ruff's unused
# import rule is waived for this file in pyproject.toml.
from sqlalchemy.dialects import postgresql

revision: str = "d857d55601e1"
down_revision: str | None = "226f3b769f0c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APP_ROLE = "sendox_app"
TENANT_PREDICATE = "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
TENANT_SCOPED_TABLES = ("contacts", "events", "products")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("first_name", sa.String(length=120), nullable=True),
        sa.Column("last_name", sa.String(length=120), nullable=True),
        sa.Column("shopify_customer_id", sa.String(length=64), nullable=True),
        sa.Column(
            "email_consent",
            sa.Enum("unknown", "subscribed", "unsubscribed", "suppressed", name="consent_state"),
            nullable=False,
        ),
        sa.Column(
            "sms_consent",
            sa.Enum("unknown", "subscribed", "unsubscribed", "suppressed", name="consent_state"),
            nullable=False,
        ),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("orders_count", sa.Integer(), nullable=False),
        sa.Column("total_spent", sa.Double(), nullable=False),
        sa.Column("last_order_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "email", name="uq_contact_tenant_email"),
    )
    op.create_index(
        "ix_contact_tenant_shopify_id",
        "contacts",
        ["tenant_id", "shopify_customer_id"],
        unique=False,
    )
    op.create_index(op.f("ix_contacts_email"), "contacts", ["email"], unique=False)
    op.create_index(op.f("ix_contacts_tenant_id"), "contacts", ["tenant_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("shopify_product_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("handle", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("product_type", sa.String(length=255), nullable=True),
        sa.Column("vendor", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("price", sa.Double(), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("image_url", sa.String(length=1024), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "shopify_product_id", name="uq_product_tenant_shopify"),
    )
    op.create_index(op.f("ix_products_tenant_id"), "products", ["tenant_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "signed_up",
                "placed_order",
                "abandoned_checkout",
                "viewed_product",
                "email_sent",
                "email_opened",
                "email_clicked",
                "email_bounced",
                "unsubscribed",
                name="event_type",
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("value", sa.Double(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "type", "external_id", name="uq_event_tenant_type_external"
        ),
    )
    op.create_index("ix_event_contact_time", "events", ["contact_id", "occurred_at"], unique=False)
    op.create_index(op.f("ix_events_contact_id"), "events", ["contact_id"], unique=False)
    op.create_index(op.f("ix_events_tenant_id"), "events", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_events_type"), "events", ["type"], unique=False)
    # ### end Alembic commands ###

    # Customer lists are the most sensitive thing this platform stores, so these
    # get the same FORCE'd policy as every other tenant-scoped table.
    for table in TENANT_SCOPED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({TENANT_PREDICATE}) WITH CHECK ({TENANT_PREDICATE})"
        )
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO {APP_ROLE}")


def downgrade() -> None:
    for table in TENANT_SCOPED_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_events_type"), table_name="events")
    op.drop_index(op.f("ix_events_tenant_id"), table_name="events")
    op.drop_index(op.f("ix_events_contact_id"), table_name="events")
    op.drop_index("ix_event_contact_time", table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_products_tenant_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_contacts_tenant_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_email"), table_name="contacts")
    op.drop_index("ix_contact_tenant_shopify_id", table_name="contacts")
    op.drop_table("contacts")
    # ### end Alembic commands ###

    # Autogenerate does not drop enum types, so a downgrade/upgrade cycle fails
    # with "type already exists" without these.
    op.execute("DROP TYPE IF EXISTS event_type")
    op.execute("DROP TYPE IF EXISTS consent_state")
